### ISSUE TITLE
Nice project

### ISSUE THREAD

**Issue by vinjn** [JLouis-B/IrrAssimp#1]
Thanks for open-sourcing it.

**Comment by JLouis-B** [comment]
Thanks !
Note that it's still a work in progress, in particular for animated models.

**Comment by vinjn** [comment]
I have noticed the issue yesterday, can I understand what the root cause is and I can offer help if possible.

**Comment by JLouis-B** [comment]
I have fixed some issues, in particular for skinned models, caused by some wrong joint matrix.
If your problem persists, you can send me a test model by mail, I will continue to work on this and make some tests this week.
And if you want to help I'm open to the contributions :-)

**Comment by vinjn** [comment]
Awesome work.
Let me try your fix later today.
By the way, have you tested some animated fbx files?

**Comment by JLouis-B** [comment]
Ok, I hope that your models give a better result than before.
I have tested one animated FBX, but I should test with more files.

**Comment by sdsunqian** [comment]
Worked like a charm. Thanks.

**Comment by netpipe** [comment]
awesome project!, had to rename dwarf.X to dwarf.x on linux or it crashs.

**Comment by JLouis-B** [comment]
Thanks.
Ok, I will change this in the main.
