### ISSUE TITLE
Wrong skinned mesh for one COLLADA mesh.

### ISSUE THREAD

**Issue by vinjn** [JLouis-B/IrrAssimp#2]
The mesh:
https://github.com/EeroHeikkinen/cinderworkshop/tree/master/Cinder-Assimp/samples/AssimpApp/assets/astroboy_walk.dae

The texture:
https://github.com/EeroHeikkinen/cinderworkshop/blob/master/Cinder-Assimp/samples/AssimpApp/assets/seymour.jpg

The buggy rendering:
![image](https://cloud.githubusercontent.com/assets/558657/7588484/fc8f2a0c-f8ef-11e4-9bd5-f02fc112423f.png)

**Comment by vinjn** [comment]
The correct result should look like

![image](https://cloud.githubusercontent.com/assets/558657/7589255/2f09adb4-f8f4-11e4-81a4-32a6a0f7e221.png)

**Comment by JLouis-B** [comment]
Ok, I will try to fix this

**Comment by vinjn** [comment]
Hi JLouis, how is it working?
I am very happy to to use this library in a new project.

**Comment by JLouis-B** [comment]
Thanks.
I havn't found the time to investigate this problem yet, many things to do currently, but I will work on this in the next weeks.

**Comment by vinjn** [comment]
Hi JLouis,

I am investigating this problem this weekend, it seems collada has different matrix semantics from other formats. However test_autodesk_DAE.DAE behaves better than test_Collada_DAE.DAE.

[The test meshes](http://219.233.31.84/www.3drt.com/3dm/free/3DRT-test-character-model.zip)

Loading mesh from Assimp: ../../media/test_directX.X
Name=Bip01_Pelvis
#0
-0.0 1.0 -0.0 0.0
1.0 0.0 0.0 0.0
0.0 -0.0 -1.0 -0.0
-9.1 -0.0 0.0 1.0

Loading mesh from Assimp: ../../media/test_Milkshape.ms3d
Name=Bip01_Pelvis
#0
-0.0 1.0 0.0 -0.0
1.0 0.0 0.0 0.0
0.0 0.0 -1.0 -0.0
-9.2 -0.0 -0.0 1.0

Loading mesh from Assimp: ../../media/test_Collada_DAE.DAE
Name=Bip01_Pelvis
#10
-0.0 0.0 1.0 0.0
-0.0 -1.0 0.0 0.0
1.0 0.0 0.0 0.0
-9.1 0.0 -0.0 1.0

Loading mesh from Assimp: ../../media/test_autodesk_DAE.DAE
Name=Bip01_Pelvis
#0
0.0 0.0 1.0 0.0
0.0 -1.0 0.0 0.0
1.0 0.0 0.0 0.0
-9.1 0.0 0.0 1.0

Do you know where could the bugs be?

**Comment by JLouis-B** [comment]
A bit longer than planned, but it's fixed.

**Comment by vinjn** [comment]
Awesome!
