### ISSUE TITLE
FBX meshes are disconnected.

### ISSUE THREAD

**Issue by vinjn** [JLouis-B/IrrAssimp#4]
The robot should have its body parts connected, however the rendering result is wrong.
The bug might be caused by incorrect R / T / S matrix calculation.

![image](https://cloud.githubusercontent.com/assets/558657/9704457/ff6b0f48-54d9-11e5-83d0-8aa303857423.png)

The problematic FBX file: https://github.com/u-engine/VrViewer/blob/master/robot.FBX

**Comment by JLouis-B** [comment]
Ok, I will investigate on this problem. (it's a problem with the nodes of the meshes)
While waiting for, a little workaround, comment line 95 in IrrAssimpImport.cpp and it will works.

**Comment by vinjn** [comment]
Thanks for the quick reply.
I am ready to help fix the problem if you could give a little more details :smile:

**Comment by JLouis-B** [comment]
At the bind pose, the nodes which contains the meshes are all positionned at (0, 0.183, 0) and the robot looks good.
And during all the animation, the nodes which contains the meshes are set to their position at the bind pose, so all the meshes are moved and it causes the bug.
You can see this in Open3DMod.
I don't know exactly what is wrong in the code (comment line 95 to disable the attachements of the meshes to the nodes works here, but it's not logical to do this, it will probably cause problem with other meshes), currently my priority will be to fix the problem described in the issue 3

**Comment by vinjn** [comment]
Ok, thx for the detailed explanation.

**Comment by vinjn** [comment]
I've applied your workaround and it did work on this fbx and another one.
However it fails some other meshes.

**Comment by vinjn** [comment]
I have some hint:

For fbx with simple node structure, we need to comment that code out:
https://github.com/u-engine/VrViewer/blob/master/robot.FBX
![r1](https://cloud.githubusercontent.com/assets/558657/9779031/247bc944-57aa-11e5-842c-c5140e33ae88.png)

For fbx with complex node structure, we need to keep it:
https://github.com/u-engine/VrViewer/blob/master/chair.fbx
![r2](https://cloud.githubusercontent.com/assets/558657/9779039/38794962-57aa-11e5-85fa-f1fd78ac0faf.png)

**Comment by JLouis-B** [comment]
Thanks for the infos

**Comment by vinjn** [comment]
Hi @JLouis-B, do we have progress on this issue?
I can provide help if you can write me some insights about why "disable the attachements of the meshes" works.

**Comment by JLouis-B** [comment]
Hi,
The issue isn't fixed yet, but I have an idea about the origin of the problem (disable the attachements of the meshes is definitely not the good solution).

I have checked the code of the Assimp viewer, the bone matrix is globalInverseMeshTransform \* globalNodeTransform \* offsetMatrix
In the case of the robot, I suppose that the globalInverseMeshTransform cancel the movement of the meshbuffer caused by the attachements of the meshes.
With you second model there is not this problem because there is no skinning.
So I think that this is the problem, the bone matrix should be computed with the globalInverseMeshTransform 
I should check how the skinning works exactly in irrlicht and find the way to fix this (maybe a little change in CSkinnedMesh will be required)

I will try to fix this the next week

**Comment by vinjn** [comment]
How does it work?

**Comment by JLouis-B** [comment]
Yes, it's a bit long, it seems complicated to solve and I'm not an expert about skinning and animations.

I have tried to change a bit the skinning in Irrlicht in CSkinnedMesh.cpp by using the globalInverseMeshTransform like I say on my last post :
http://pastebin.com/YNEKr8FP
It seems to solve the problem.
It should be optimised and I should do more tests

Are you able to export the robot in the directx format and reproduce the issue ? (without try to patch CSkinnedMesh) ?
It can be useful for my tests.

**Comment by vinjn** [comment]
I don't have the original mesh file, so I am not able to convert it.
I would like to test your hot fix.

On Thu, Oct 8, 2015 at 10:41 PM, Jean-Louis Boudrand <
notifications@github.com> wrote:

> Yes, it's a bit long, it seems complicated to solve and I'm not an expert
> about skinning and animations.
> 
> I have tried to change a bit the skinning in Irrlicht in CSkinnedMesh.cpp
> by using the globalInverseMeshTransform like I say on my last post :
> http://pastebin.com/YNEKr8FP
> It seems to solve the problem.
> It should be optimised and I should do more tests
> 
> Are you able to export the robot in the directx format and reproduce the
> issue ? (without try to patch CSkinnedMesh) ?
> It can be useful for my tests.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JLouis-B/IrrAssimp/issues/4#issuecomment-146566819.

## 

Vinjn Zhang 张静
http://vinjn.github.io/
+86 137 6451 5898

**Comment by vinjn** [comment]
That fix works, awesome!

**Comment by vinjn** [comment]
The inverse matrix can be cached for optimization.
