### ISSUE TITLE
Which Version? 

### ISSUE THREAD

**Issue by vutranclan** [JLouis-B/IrrAssimp#5]
Which Version of irrlicht und Assimp Do i need?

**Comment by JLouis-B** [comment]
The code works with the latest versions of Irrlicht and Assimp, and it can probably also works with an older version of these librabries.

**Comment by vutranclan** [comment]
i have the newsest version of both. and try to make it run with irrAssimp.
When i compile i always get this. Can you send me a running version?

1>------ Build started: Project: 01.HelloWorld_vc9, Configuration: Debug Win32 ------
1>Linking...
1>main.obj : error LNK2019: unresolved external symbol "public: virtual __thiscall IrrAssimp::~IrrAssimp(void)" (??1IrrAssimp@@UAE@XZ) referenced in function _main
1>main.obj : error LNK2019: unresolved external symbol "public: bool __thiscall IrrAssimp::exportMesh(class irr::scene::IMesh *,class irr::core::string<char,class irr::core::irrAllocator<char> >,class irr::core::string<char,class irr::core::irrAllocator<char> >)" (?exportMesh@IrrAssimp@@QAE_NPAVIMesh@scene@irr@@V?$string@DV?$irrAllocator@D@core@irr@@@core@4@1@Z) referenced in function _main
1>main.obj : error LNK2019: unresolved external symbol "public: class irr::scene::IAnimatedMesh \* __thiscall IrrAssimp::getMesh(class irr::core::string<char,class irr::core::irrAllocator<char> > const &)" (?getMesh@IrrAssimp@@QAEPAVIAnimatedMesh@scene@irr@@ABV?$string@DV?$irrAllocator@D@core@irr@@@core@4@@Z) referenced in function _main
1>main.obj : error LNK2019: unresolved external symbol "public: __thiscall IrrAssimp::IrrAssimp(class irr::scene::ISceneManager *)" (??0IrrAssimp@@QAE@PAVISceneManager@scene@irr@@@Z) referenced in function _main
1>....\bin\Win32-VisualStudio\01.HelloWorld.exe : fatal error LNK1120: 4 unresolved externals
1>Build log was saved at "file://c:\Users\mrui\Desktop\IrrAssimp-master\Debug\BuildLog.htm"
1>01.HelloWorld_vc9 - 5 error(s), 0 warning(s)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by JLouis-B** [comment]
The VS files aren't up to date, you should add all the files of the subfolder "IrrAssimp" to your project to fix the errors.
Also I have just made a commit in the "BonesSkinning" branch to fix a compilation error with VS.
